version: '3.1'
services:

  review_service-db:
    image: postgres:13.7-alpine
    container_name: review_service-db
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=review
      - POSTGRES_USER=review
      - POSTGRES_PASSWORD=review

  review_service:
    build: .
    container_name: review_service
    ports:
      - "8084:8084"
    depends_on:
      - review_service-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://review_service-db:5432/review
      - SPRING_DATASOURCE_USERNAME=review
      - SPRING_DATASOURCE_PASSWORD=review
