--liquibase formatted sql
--changeset ism:create-tables

CREATE TABLE reviews(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    username VARCHAR(256) NOT NULL,
    title VARCHAR(256) NOT NULL,
    content_text VARCHAR(256) NOT NULL,
    create_time TIMESTAMP NOT NULL,
    update_time TIMESTAMP,
    mark BIGINT,
    event_id BIGINT NOT NULL
)